# Generated by Django 3.2.9 on 2021-12-19 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(default='shoes/default.png', upload_to='shoes')),
                ('genderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeNumb', models.IntegerField(default=0)),
                ('sizeAmount', models.PositiveIntegerField(default=0)),
                ('shoeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='OrderShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField()),
                ('shoeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike.shoe')),
                ('sizeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike.size')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=100)),
                ('contactSubject', models.CharField(max_length=100)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactMessage', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
